---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-devops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-devops
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      imagePullSecrets:
      - name: default-secret
      containers:
      - name: nodejs-app
        image: {{ swrURL }}/{{ orgName }}/{{ imageName }}:{{ buildVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080